// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientMonitoringControl.proto

package ds.serviceThree;

public interface PatUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.PatUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
