// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientMonitoringControl.proto

package ds.serviceThree;

public final class ServiceThreeImpl {
  private ServiceThreeImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_VitCheckerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_VitCheckerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_VitCheckerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_VitCheckerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_PatUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_PatUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_PatUpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_PatUpdateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036PatientMonitoringControl.proto\022\010servic" +
      "e3\"!\n\021VitCheckerRequest\022\014\n\004text\030\001 \001(\t\"&\n" +
      "\022VitCheckerResponse\022\020\n\010textback\030\001 \001(\t\" \n" +
      "\020PatUpdateRequest\022\014\n\004text\030\001 \001(\t\"%\n\021PatUp" +
      "dateResponse\022\020\n\010textback\030\001 \001(\t2\270\001\n\030Patie" +
      "ntMonitoringControl\022P\n\rVitalsChecker\022\033.s" +
      "ervice3.VitCheckerRequest\032\034.service3.Vit" +
      "CheckerResponse\"\000(\0010\001\022J\n\rPatientUpdate\022\032" +
      ".service3.PatUpdateRequest\032\033.service3.Pa" +
      "tUpdateResponse\"\000B%\n\017ds.serviceThreeB\020Se" +
      "rviceThreeImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service3_VitCheckerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service3_VitCheckerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_VitCheckerRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_service3_VitCheckerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service3_VitCheckerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_VitCheckerResponse_descriptor,
        new java.lang.String[] { "Textback", });
    internal_static_service3_PatUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service3_PatUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_PatUpdateRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_service3_PatUpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service3_PatUpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_PatUpdateResponse_descriptor,
        new java.lang.String[] { "Textback", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
