// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientMonitoringControl.proto

package ds.serviceThree;

public interface VitCheckerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.VitCheckerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string textback = 1;</code>
   */
  java.lang.String getTextback();
  /**
   * <code>string textback = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextbackBytes();
}
