// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PersonalHealthAssistant.proto

package ds.serviceTwo;

public interface BMICalcResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.BMICalcResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 result = 1;</code>
   */
  int getResult();
}
