// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PersonalHealthAssistant.proto

package ds.serviceTwo;

public interface BMICalcRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.BMICalcRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 weigth = 1;</code>
   */
  int getWeigth();

  /**
   * <code>int32 height = 2;</code>
   */
  int getHeight();
}
