// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PersonalHealthAssistant.proto

package ds.serviceTwo;

public interface MedStockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.MedStockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
