// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WellBeingChecker.proto

package ds.serviceOne;

public interface PulseReadResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.PulseReadResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string textback = 1;</code>
   */
  java.lang.String getTextback();
  /**
   * <code>string textback = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextbackBytes();
}
