// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WellBeingChecker.proto

package ds.serviceOne;

public interface PulseReadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.PulseReadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 num = 1;</code>
   */
  int getNum();
}
