// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WellBeingChecker.proto

package ds.serviceOne;

public final class ServiceOneImpl {
  private ServiceOneImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_PulseReadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_PulseReadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_PulseReadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_PulseReadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_StepsCalcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_StepsCalcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_StepsCalcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_StepsCalcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026WellBeingChecker.proto\022\010service1\"\037\n\020Pu" +
      "lseReadRequest\022\013\n\003num\030\001 \001(\005\"%\n\021PulseRead" +
      "Response\022\020\n\010textback\030\001 \001(\t\"!\n\020StepsCalcR" +
      "equest\022\r\n\005steps\030\001 \001(\005\"8\n\021StepsCalcRespon" +
      "se\022\020\n\010textback\030\001 \001(\t\022\021\n\tstepsleft\030\002 \001(\0052" +
      "\261\001\n\020WellBeingChecker\022M\n\014PulseReading\022\032.s" +
      "ervice1.PulseReadRequest\032\033.service1.Puls" +
      "eReadResponse\"\000(\0010\001\022N\n\017StepsCalculator\022\032" +
      ".service1.StepsCalcRequest\032\033.service1.St" +
      "epsCalcResponse\"\000(\001B!\n\rds.serviceOneB\016Se" +
      "rviceOneImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service1_PulseReadRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1_PulseReadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_PulseReadRequest_descriptor,
        new java.lang.String[] { "Num", });
    internal_static_service1_PulseReadResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1_PulseReadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_PulseReadResponse_descriptor,
        new java.lang.String[] { "Textback", });
    internal_static_service1_StepsCalcRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service1_StepsCalcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_StepsCalcRequest_descriptor,
        new java.lang.String[] { "Steps", });
    internal_static_service1_StepsCalcResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service1_StepsCalcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_StepsCalcResponse_descriptor,
        new java.lang.String[] { "Textback", "Stepsleft", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
