// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WellBeingChecker.proto

package ds.serviceOne;

public final class ServiceOneImpl {
  private ServiceOneImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_PulseReadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_PulseReadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_PulseReadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_PulseReadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_StepsCalcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_StepsCalcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_StepsCalcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_StepsCalcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026WellBeingChecker.proto\022\010service1\" \n\020Pu" +
      "lseReadRequest\022\014\n\004text\030\001 \001(\t\"%\n\021PulseRea" +
      "dResponse\022\020\n\010textback\030\001 \001(\t\" \n\020StepsCalc" +
      "Request\022\014\n\004text\030\001 \001(\t\"%\n\021StepsCalcRespon" +
      "se\022\020\n\010textback\030\001 \001(\t2\261\001\n\020WellBeingChecke" +
      "r\022M\n\014PulseReading\022\032.service1.PulseReadRe" +
      "quest\032\033.service1.PulseReadResponse\"\000(\0010\001" +
      "\022N\n\017StepsCalculator\022\032.service1.StepsCalc" +
      "Request\032\033.service1.StepsCalcResponse\"\000(\001" +
      "B!\n\rds.serviceOneB\016ServiceOneImplP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service1_PulseReadRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1_PulseReadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_PulseReadRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_service1_PulseReadResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1_PulseReadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_PulseReadResponse_descriptor,
        new java.lang.String[] { "Textback", });
    internal_static_service1_StepsCalcRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service1_StepsCalcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_StepsCalcRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_service1_StepsCalcResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service1_StepsCalcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_StepsCalcResponse_descriptor,
        new java.lang.String[] { "Textback", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
