// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WellBeingChecker.proto

package ds.serviceOne;

/**
 * Protobuf type {@code service1.StepsCalcResponse}
 */
public  final class StepsCalcResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service1.StepsCalcResponse)
    StepsCalcResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StepsCalcResponse.newBuilder() to construct.
  private StepsCalcResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StepsCalcResponse() {
    textback_ = "";
    stepsleft_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StepsCalcResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            textback_ = s;
            break;
          }
          case 16: {

            stepsleft_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.serviceOne.ServiceOneImpl.internal_static_service1_StepsCalcResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.serviceOne.ServiceOneImpl.internal_static_service1_StepsCalcResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.serviceOne.StepsCalcResponse.class, ds.serviceOne.StepsCalcResponse.Builder.class);
  }

  public static final int TEXTBACK_FIELD_NUMBER = 1;
  private volatile java.lang.Object textback_;
  /**
   * <code>string textback = 1;</code>
   */
  public java.lang.String getTextback() {
    java.lang.Object ref = textback_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      textback_ = s;
      return s;
    }
  }
  /**
   * <code>string textback = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTextbackBytes() {
    java.lang.Object ref = textback_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      textback_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STEPSLEFT_FIELD_NUMBER = 2;
  private int stepsleft_;
  /**
   * <code>int32 stepsleft = 2;</code>
   */
  public int getStepsleft() {
    return stepsleft_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTextbackBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, textback_);
    }
    if (stepsleft_ != 0) {
      output.writeInt32(2, stepsleft_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTextbackBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, textback_);
    }
    if (stepsleft_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, stepsleft_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.serviceOne.StepsCalcResponse)) {
      return super.equals(obj);
    }
    ds.serviceOne.StepsCalcResponse other = (ds.serviceOne.StepsCalcResponse) obj;

    boolean result = true;
    result = result && getTextback()
        .equals(other.getTextback());
    result = result && (getStepsleft()
        == other.getStepsleft());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEXTBACK_FIELD_NUMBER;
    hash = (53 * hash) + getTextback().hashCode();
    hash = (37 * hash) + STEPSLEFT_FIELD_NUMBER;
    hash = (53 * hash) + getStepsleft();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.serviceOne.StepsCalcResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.serviceOne.StepsCalcResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.serviceOne.StepsCalcResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.serviceOne.StepsCalcResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.serviceOne.StepsCalcResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.serviceOne.StepsCalcResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.serviceOne.StepsCalcResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.serviceOne.StepsCalcResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.serviceOne.StepsCalcResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.serviceOne.StepsCalcResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.serviceOne.StepsCalcResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.serviceOne.StepsCalcResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.serviceOne.StepsCalcResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code service1.StepsCalcResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service1.StepsCalcResponse)
      ds.serviceOne.StepsCalcResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.serviceOne.ServiceOneImpl.internal_static_service1_StepsCalcResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.serviceOne.ServiceOneImpl.internal_static_service1_StepsCalcResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.serviceOne.StepsCalcResponse.class, ds.serviceOne.StepsCalcResponse.Builder.class);
    }

    // Construct using ds.serviceOne.StepsCalcResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      textback_ = "";

      stepsleft_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.serviceOne.ServiceOneImpl.internal_static_service1_StepsCalcResponse_descriptor;
    }

    @java.lang.Override
    public ds.serviceOne.StepsCalcResponse getDefaultInstanceForType() {
      return ds.serviceOne.StepsCalcResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ds.serviceOne.StepsCalcResponse build() {
      ds.serviceOne.StepsCalcResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.serviceOne.StepsCalcResponse buildPartial() {
      ds.serviceOne.StepsCalcResponse result = new ds.serviceOne.StepsCalcResponse(this);
      result.textback_ = textback_;
      result.stepsleft_ = stepsleft_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.serviceOne.StepsCalcResponse) {
        return mergeFrom((ds.serviceOne.StepsCalcResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.serviceOne.StepsCalcResponse other) {
      if (other == ds.serviceOne.StepsCalcResponse.getDefaultInstance()) return this;
      if (!other.getTextback().isEmpty()) {
        textback_ = other.textback_;
        onChanged();
      }
      if (other.getStepsleft() != 0) {
        setStepsleft(other.getStepsleft());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.serviceOne.StepsCalcResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.serviceOne.StepsCalcResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object textback_ = "";
    /**
     * <code>string textback = 1;</code>
     */
    public java.lang.String getTextback() {
      java.lang.Object ref = textback_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        textback_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string textback = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextbackBytes() {
      java.lang.Object ref = textback_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        textback_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string textback = 1;</code>
     */
    public Builder setTextback(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      textback_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string textback = 1;</code>
     */
    public Builder clearTextback() {
      
      textback_ = getDefaultInstance().getTextback();
      onChanged();
      return this;
    }
    /**
     * <code>string textback = 1;</code>
     */
    public Builder setTextbackBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      textback_ = value;
      onChanged();
      return this;
    }

    private int stepsleft_ ;
    /**
     * <code>int32 stepsleft = 2;</code>
     */
    public int getStepsleft() {
      return stepsleft_;
    }
    /**
     * <code>int32 stepsleft = 2;</code>
     */
    public Builder setStepsleft(int value) {
      
      stepsleft_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 stepsleft = 2;</code>
     */
    public Builder clearStepsleft() {
      
      stepsleft_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service1.StepsCalcResponse)
  }

  // @@protoc_insertion_point(class_scope:service1.StepsCalcResponse)
  private static final ds.serviceOne.StepsCalcResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.serviceOne.StepsCalcResponse();
  }

  public static ds.serviceOne.StepsCalcResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StepsCalcResponse>
      PARSER = new com.google.protobuf.AbstractParser<StepsCalcResponse>() {
    @java.lang.Override
    public StepsCalcResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StepsCalcResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StepsCalcResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StepsCalcResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.serviceOne.StepsCalcResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

